### ISSUE TITLE
sci-libs/cblas-reference-20151113-r2 fails to build

### ISSUE THREAD

**Issue by jhyeon** [gentoo-science/sci#549]
On my system,
```
# emerge =sci-libs/cblas-reference-20151113-r2::science
```
fails.  The output of `emerge --info '=sci-libs/cblas-reference-20151113-r2::science'`, the complete build log and the output of `emerge -pqv '=sci-libs/cblas-reference-20151113-r2::science'` are attached.
[emerge--info.txt](https://github.com/gentoo-science/sci/files/54373/emerge--info.txt)
[build.log.txt](https://github.com/gentoo-science/sci/files/54374/build.log.txt)
[emerge-pqv.txt](https://github.com/gentoo-science/sci/files/54375/emerge-pqv.txt)

**Comment by SoapZaNet** [comment]
Try running `eselect blas set reference` before the emerge, it clearly can't find the `blas.pc` pkg-config file.

**Comment by SoapZaNet** [comment]
So we were missing the blas dependency, resync and try again please.

**Comment by jlec** [comment]
Should be fixed in b49c63f8cc6553462f345d35554dc2661400cf51

**Comment by jhyeon** [comment]
I already had `sci-libs/atlas[fortran]` installed which fulfils the dependence on `virtual/blas`, so I doubt that b49c63f8cc6553462f345d35554dc2661400cf51 is a complete fix.  Indeed, simple resync did not resolve the build failure of `cblas-reference`.  However, doing `emerge sci-libs/blas-reference` and `eselect blas set reference` manually did work.  I wonder why `cblas-reference` fails to find `blas` from `atlas`.

**Comment by jhyeon** [comment]
The reason seems to be that atlas does not support multilib.

**Comment by jlec** [comment]
@jhyeon why do you need the 32bit libs if I may ask?

**Comment by jhyeon** [comment]
I enable 32bit libs globally by having
```
ABI_X86="64 32"
```
in `make.conf` to run some 32bit applications such as `acroread` and `skype`.  However, I now suppose it is unlikely that any of them would need 32bit `(c)blas`.

**Comment by jlec** [comment]
Don't do that. That is absolutely unnecessary. emerge will automatically handle deps for ```acroread```and ```skype```. Enabling this globally just creates longer compile times, uses up more diskspace and let's you run in unnecessary bugs like this one.

**Comment by jhyeon** [comment]
In fact, I did so following a (perhaps outdated) guide like http://www.funtoo.org/News:ABI_X86_64_and_32.  However, when I tried removing the `ABI_X86` setting and rebuilding the system, it just worked!  Thanks a lot for the hint!
